export interface AnswerEntry {
  word: string;
  category: string;
}

export const GLYPH_CATEGORIES = [
  "animal",
  "food",
  "plant",
  "nature",
  "object",
  "place",
  "action",
  "body",
  "music",
  "tech",
  "feeling",
  "time",
  "color",
  "person",
  "science",
] as const;

export const ANSWER_WORDS: readonly AnswerEntry[] = [
  { word: "zebra", category: "animal" },
  { word: "tiger", category: "animal" },
  { word: "horse", category: "animal" },
  { word: "mouse", category: "animal" },
  { word: "snake", category: "animal" },
  { word: "whale", category: "animal" },
  { word: "shark", category: "animal" },
  { word: "sheep", category: "animal" },
  { word: "koala", category: "animal" },
  { word: "llama", category: "animal" },
  { word: "otter", category: "animal" },
  { word: "panda", category: "animal" },
  { word: "eagle", category: "animal" },
  { word: "crane", category: "animal" },
  { word: "goose", category: "animal" },
  { word: "moose", category: "animal" },
  { word: "camel", category: "animal" },
  { word: "rhino", category: "animal" },
  { word: "sloth", category: "animal" },
  { word: "robin", category: "animal" },
  { word: "finch", category: "animal" },
  { word: "heron", category: "animal" },
  { word: "trout", category: "animal" },
  { word: "squid", category: "animal" },
  { word: "snail", category: "animal" },
  { word: "gecko", category: "animal" },
  { word: "cobra", category: "animal" },
  { word: "raven", category: "animal" },
  { word: "quail", category: "animal" },
  { word: "puppy", category: "animal" },
  { word: "bison", category: "animal" },
  { word: "hyena", category: "animal" },
  { word: "viper", category: "animal" },
  { word: "bread", category: "food" },
  { word: "toast", category: "food" },
  { word: "honey", category: "food" },
  { word: "sugar", category: "food" },
  { word: "lemon", category: "food" },
  { word: "mango", category: "food" },
  { word: "peach", category: "food" },
  { word: "grape", category: "food" },
  { word: "olive", category: "food" },
  { word: "pasta", category: "food" },
  { word: "pizza", category: "food" },
  { word: "salad", category: "food" },
  { word: "juice", category: "food" },
  { word: "cream", category: "food" },
  { word: "candy", category: "food" },
  { word: "cocoa", category: "food" },
  { word: "berry", category: "food" },
  { word: "melon", category: "food" },
  { word: "onion", category: "food" },
  { word: "basil", category: "food" },
  { word: "thyme", category: "food" },
  { word: "wheat", category: "food" },
  { word: "dough", category: "food" },
  { word: "jelly", category: "food" },
  { word: "sushi", category: "food" },
  { word: "bagel", category: "food" },
  { word: "flour", category: "food" },
  { word: "cider", category: "food" },
  { word: "maple", category: "food" },
  { word: "grass", category: "plant" },
  { word: "plant", category: "plant" },
  { word: "tulip", category: "plant" },
  { word: "daisy", category: "plant" },
  { word: "birch", category: "plant" },
  { word: "cedar", category: "plant" },
  { word: "petal", category: "plant" },
  { word: "thorn", category: "plant" },
  { word: "bloom", category: "plant" },
  { word: "lotus", category: "plant" },
  { word: "river", category: "nature" },
  { word: "cloud", category: "nature" },
  { word: "storm", category: "nature" },
  { word: "frost", category: "nature" },
  { word: "stone", category: "nature" },
  { word: "ocean", category: "nature" },
  { word: "beach", category: "nature" },
  { word: "creek", category: "nature" },
  { word: "shore", category: "nature" },
  { word: "ridge", category: "nature" },
  { word: "field", category: "nature" },
  { word: "grove", category: "nature" },
  { word: "marsh", category: "nature" },
  { word: "cliff", category: "nature" },
  { word: "flame", category: "nature" },
  { word: "ember", category: "nature" },
  { word: "spark", category: "nature" },
  { word: "light", category: "nature" },
  { word: "shade", category: "nature" },
  { word: "sunny", category: "nature" },
  { word: "chair", category: "object" },
  { word: "table", category: "object" },
  { word: "clock", category: "object" },
  { word: "phone", category: "object" },
  { word: "brush", category: "object" },
  { word: "glass", category: "object" },
  { word: "plate", category: "object" },
  { word: "knife", category: "object" },
  { word: "spoon", category: "object" },
  { word: "torch", category: "object" },
  { word: "bench", category: "object" },
  { word: "shelf", category: "object" },
  { word: "frame", category: "object" },
  { word: "wheel", category: "object" },
  { word: "brick", category: "object" },
  { word: "fence", category: "object" },
  { word: "hinge", category: "object" },
  { word: "latch", category: "object" },
  { word: "glove", category: "object" },
  { word: "scarf", category: "object" },
  { word: "boots", category: "object" },
  { word: "crown", category: "object" },
  { word: "sword", category: "object" },
  { word: "arrow", category: "object" },
  { word: "badge", category: "object" },
  { word: "cable", category: "object" },
  { word: "motor", category: "object" },
  { word: "robot", category: "object" },
  { word: "canoe", category: "object" },
  { word: "plane", category: "object" },
  { word: "train", category: "object" },
  { word: "truck", category: "object" },
  { word: "wagon", category: "object" },
  { word: "piano", category: "object" },
  { word: "flute", category: "object" },
  { word: "radio", category: "object" },
  { word: "video", category: "object" },
  { word: "laser", category: "object" },
  { word: "prism", category: "object" },
  { word: "pixel", category: "object" },
  { word: "cabin", category: "place" },
  { word: "hotel", category: "place" },
  { word: "house", category: "place" },
  { word: "store", category: "place" },
  { word: "plaza", category: "place" },
  { word: "attic", category: "place" },
  { word: "porch", category: "place" },
  { word: "alley", category: "place" },
  { word: "court", category: "place" },
  { word: "arena", category: "place" },
  { word: "tower", category: "place" },
  { word: "vault", category: "place" },
  { word: "dance", category: "action" },
  { word: "chase", category: "action" },
  { word: "climb", category: "action" },
  { word: "laugh", category: "action" },
  { word: "dream", category: "action" },
  { word: "think", category: "action" },
  { word: "speak", category: "action" },
  { word: "write", category: "action" },
  { word: "learn", category: "action" },
  { word: "teach", category: "action" },
  { word: "guard", category: "action" },
  { word: "march", category: "action" },
  { word: "paint", category: "action" },
  { word: "sleep", category: "action" },
  { word: "solve", category: "action" },
  { word: "build", category: "action" },
  { word: "break", category: "action" },
  { word: "catch", category: "action" },
  { word: "throw", category: "action" },
  { word: "watch", category: "action" },
  { word: "touch", category: "action" },
  { word: "smell", category: "action" },
  { word: "taste", category: "action" },
  { word: "heart", category: "body" },
  { word: "brain", category: "body" },
  { word: "nerve", category: "body" },
  { word: "spine", category: "body" },
  { word: "blood", category: "body" },
  { word: "bones", category: "body" },
  { word: "cheek", category: "body" },
  { word: "thumb", category: "body" },
  { word: "wrist", category: "body" },
  { word: "elbow", category: "body" },
  { word: "teeth", category: "body" },
  { word: "mouth", category: "body" },
  { word: "voice", category: "body" },
  { word: "smile", category: "body" },
  { word: "tears", category: "body" },
  { word: "chord", category: "music" },
  { word: "tempo", category: "music" },
  { word: "notes", category: "music" },
  { word: "sound", category: "music" },
  { word: "vocal", category: "music" },
  { word: "album", category: "music" },
  { word: "drums", category: "music" },
  { word: "email", category: "tech" },
  { word: "error", category: "tech" },
  { word: "query", category: "tech" },
  { word: "cache", category: "tech" },
  { word: "cyber", category: "tech" },
  { word: "bytes", category: "tech" },
  { word: "input", category: "tech" },
  { word: "array", category: "tech" },
  { word: "stack", category: "tech" },
  { word: "queue", category: "tech" },
  { word: "debug", category: "tech" },
  { word: "logic", category: "tech" },
  { word: "model", category: "tech" },
  { word: "brave", category: "feeling" },
  { word: "happy", category: "feeling" },
  { word: "angry", category: "feeling" },
  { word: "proud", category: "feeling" },
  { word: "eager", category: "feeling" },
  { word: "quiet", category: "feeling" },
  { word: "sorry", category: "feeling" },
  { word: "worry", category: "feeling" },
  { word: "peace", category: "feeling" },
  { word: "trust", category: "feeling" },
  { word: "loyal", category: "feeling" },
  { word: "vivid", category: "feeling" },
  { word: "dizzy", category: "feeling" },
  { word: "jolly", category: "feeling" },
  { word: "lucky", category: "feeling" },
  { word: "funny", category: "feeling" },
  { word: "today", category: "time" },
  { word: "night", category: "time" },
  { word: "early", category: "time" },
  { word: "later", category: "time" },
  { word: "never", category: "time" },
  { word: "often", category: "time" },
  { word: "since", category: "time" },
  { word: "until", category: "time" },
  { word: "green", category: "color" },
  { word: "black", category: "color" },
  { word: "white", category: "color" },
  { word: "brown", category: "color" },
  { word: "amber", category: "color" },
  { word: "azure", category: "color" },
  { word: "child", category: "person" },
  { word: "woman", category: "person" },
  { word: "uncle", category: "person" },
  { word: "coach", category: "person" },
  { word: "chief", category: "person" },
  { word: "guest", category: "person" },
  { word: "queen", category: "person" },
  { word: "solar", category: "science" },
  { word: "lunar", category: "science" },
  { word: "orbit", category: "science" },
  { word: "study", category: "science" },
];

export const EXTRA_VALID: readonly string[] = [
  "about", "above", "actor", "adapt", "admit", "adopt", "adult", "after", "again", "agent",
  "agree", "ahead", "alarm", "alert", "alike", "alive", "allow", "alone", "along", "alter",
  "among", "angle", "ankle", "apart", "apple", "apply", "argue", "arise", "armor", "aside",
  "asset", "avoid", "awake", "award", "aware", "awful", "baked", "basic", "basin", "batch",
  "began", "begin", "being", "below", "birth", "blade", "blame", "blank", "blast", "blend",
  "bless", "blind", "block", "board", "boast", "boost", "booth", "bound", "brand", "brass",
  "breed", "brief", "bring", "broad", "broke", "carry", "cause", "chain", "chart", "cheer",
  "chess", "chest", "claim", "class", "clean", "clear", "click", "close", "cloth", "coast",
  "count", "cover", "craft", "crash", "crazy", "crisp", "cross", "crowd", "curve", "cycle",
  "daily", "dealt", "delay", "dense", "depth", "diary", "dirty", "doubt", "dozen", "draft",
  "drain", "drama", "drank", "drawn", "dress", "drift", "drink", "drive", "drove", "earth",
  "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal", "equip", "event",
  "every", "exact", "exist", "extra", "faith", "false", "fancy", "fatal", "fault", "favor",
  "feast", "fever", "fiber", "fifth", "fight", "final", "first", "fixed", "flash", "fleet",
  "flesh", "flint", "focus", "force", "forth", "forty", "forum", "found", "frank", "fraud",
  "fresh", "front", "fruit", "fully", "giant", "given", "grace", "grade", "grain", "grand",
  "grant", "graph", "grasp", "great", "grief", "gross", "group", "grown", "guess", "guide",
  "harsh", "haste", "hatch", "haunt", "heavy", "hello", "hobby", "honor", "human", "humor",
  "ideal", "image", "index", "inner", "irony", "issue", "ivory", "jeans", "jewel", "joint",
  "judge", "knock", "known", "label", "labor", "large", "layer", "lease", "least", "leave",
  "legal", "level", "lever", "limit", "linen", "local", "lodge", "loose", "lorry", "lower",
  "lunch", "lyric", "magic", "major", "maker", "marry", "match", "maybe", "mayor", "medal",
  "media", "mercy", "merit", "metal", "meter", "might", "minor", "mixed", "money", "month",
  "moral", "mount", "movie", "music", "newly", "noble", "noise", "north", "novel", "nurse",
  "oasis", "occur", "offer", "opera", "order", "other", "ought", "ounce", "outer", "owner",
  "oxide", "panel", "panic", "paper", "party", "patch", "pause", "pearl", "pedal", "penny",
  "phase", "photo", "piece", "pilot", "pinch", "pitch", "place", "plain", "point", "pound",
  "power", "press", "price", "pride", "prime", "print", "prior", "prize", "proof", "prove",
  "pulse", "punch", "pupil", "purse", "quest", "quick", "quite", "quota", "radar", "raise",
  "rally", "ranch", "range", "rapid", "ratio", "reach", "react", "ready", "realm", "rebel",
  "refer", "reign", "relax", "relay", "reply", "rider", "rifle", "right", "rigid", "roast",
  "rocky", "roman", "rough", "round", "route", "royal", "rural", "scale", "scent", "scene",
  "scope", "score", "scout", "screw", "sense", "serve", "seven", "shake", "shall", "shape",
  "share", "sharp", "sheet", "shell", "shift", "shine", "shirt", "shock", "shoot", "short",
  "shown", "sight", "sixth", "sixty", "skill", "slice", "slide", "smoke", "solid", "south",
  "space", "speed", "spell", "spend", "spent", "spice", "spike", "split", "spoke", "sport",
  "staff", "stage", "stair", "stake", "stamp", "stand", "stare", "start", "state", "steam",
  "steel", "steep", "stick", "still", "stock", "stood", "story", "stove", "strip", "stuck",
  "stuff", "style", "suite", "super", "surge", "sweet", "taken", "tally", "tenth", "thank",
  "theft", "their", "theme", "there", "these", "thick", "thing", "third", "those", "three",
  "threw", "tight", "timer", "tired", "title", "token", "tooth", "topic", "total", "tough",
  "toxic", "trace", "track", "trade", "trail", "trait", "trash", "treat", "trend", "trial",
  "tribe", "trick", "tried", "troop", "truly", "trunk", "truth", "twice", "twist", "under",
  "union", "unite", "upper", "upset", "urban", "usage", "usual", "valid", "value", "vapor",
  "venue", "verse", "villa", "vinyl", "viral", "virus", "visit", "vital", "voter", "waist",
  "waste", "water", "weary", "weave", "wedge", "weigh", "weird", "where", "which", "while",
  "whole", "whose", "widow", "width", "witch", "world", "worse", "worst", "worth", "would",
  "wrong", "wrote", "yacht", "young", "youth", "zones", "bobby", "eerie", "kebab",
  "adieu", "audio", "slate", "crate", "roate", "salet", "soare", "alien", "gamer", "chill",
  "blaze", "glory", "swift", "smart", "forge", "anvil", "flock", "swarm", "trees", "roots",
  "seeds", "salty", "spicy", "tasty", "steak", "sauce", "snack", "ghost", "lance",
];

export const VALID_WORDS: readonly string[] = Array.from(
  new Set([...ANSWER_WORDS.map((entry) => entry.word), ...EXTRA_VALID]),
);
