export interface WordCategory {
  name: string;
  themeColor: string;
  words: string[];
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    name: "CYBER TECH",
    themeColor: "#00FFA3",
    words: [
      "CYBER",
      "MATRIX",
      "LASER",
      "PIXEL",
      "QUANTUM",
      "SYNTH",
      "CIRCUIT",
      "GLITCH",
      "ROBOT",
      "NEON",
      "VECTOR",
      "BYTE",
      "NANO",
      "DATA",
      "SIGNAL",
      "HACK",
    ],
  },
  {
    name: "DEEP SPACE",
    themeColor: "#4FC3FF",
    words: [
      "GALAXY",
      "COMET",
      "NEBULA",
      "ORBIT",
      "SOLAR",
      "PULSAR",
      "COSMOS",
      "PLANET",
      "METEOR",
      "ECLIPSE",
      "ASTEROID",
      "STAR",
      "LUNAR",
      "VOID",
      "ZENITH",
    ],
  },
  {
    name: "NEON BEASTS",
    themeColor: "#FF007F",
    words: [
      "PANTHER",
      "FALCON",
      "TIGER",
      "VIPER",
      "COBRA",
      "EAGLE",
      "WOLF",
      "DRAGON",
      "SHARK",
      "PHOENIX",
      "GRIFFIN",
      "JAGUAR",
      "LION",
      "RAVEN",
      "BEAR",
    ],
  },
  {
    name: "COSMIC ELEMENTS",
    themeColor: "#FFD700",
    words: [
      "AURORA",
      "CRYSTAL",
      "PLASMA",
      "FLAME",
      "VORTEX",
      "PRISM",
      "LIGHTNING",
      "SHADOW",
      "THUNDER",
      "FROST",
      "SPARK",
      "QUARTZ",
      "BLAZE",
      "EMBER",
    ],
  },
  {
    name: "RETRO ARCADE",
    themeColor: "#E056FD",
    words: [
      "PINBALL",
      "JOYSTICK",
      "INVADER",
      "TETRIS",
      "COMBO",
      "HIGHSCORE",
      "BONANZA",
      "REPLAY",
      "COIN",
      "LEVEL",
      "STAGE",
      "BONUS",
      "SCORE",
      "QUEST",
    ],
  },
];
