export interface WordCategory {
  name: string;
  themeColor: string;
  words: string[];
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    name: "CYBER TECH",
    themeColor: "#00FFA3",
    words: [
      "CYBERSPACE",
      "BLOCKCHAIN",
      "ALGORITHM",
      "MAINFRAME",
      "NANOBOTS",
      "ENCRYPTION",
      "INTERFACE",
      "SYNCHRONY",
      "QUANTUM",
      "HOLOGRAM",
      "PROCESSOR",
      "CIRCUIT",
      "MATRIX",
      "PIXEL",
      "SYNTH",
      "LASER",
      "GLITCH",
      "ROBOT",
      "VECTOR",
    ],
  },
  {
    name: "DEEP SPACE",
    themeColor: "#4FC3FF",
    words: [
      "SUPERNOVA",
      "CONSTELLATION",
      "EXOPLANET",
      "GRAVITATION",
      "INTERSTELLAR",
      "SINGULARITY",
      "ASTEROIDS",
      "TELESCOPE",
      "METEORITE",
      "ATMOSPHERE",
      "GALAXY",
      "NEBULA",
      "PULSAR",
      "COSMOS",
      "PLANET",
      "ECLIPSE",
      "ORBIT",
      "SOLAR",
      "COMET",
    ],
  },
  {
    name: "NEON BEASTS",
    themeColor: "#FF007F",
    words: [
      "VELOCIRAPTOR",
      "CHAMELEON",
      "SALAMANDER",
      "TYRANNOSAUR",
      "BARRACUDA",
      "TARANTULA",
      "LEOPARD",
      "PANTHER",
      "PHOENIX",
      "GRIFFIN",
      "FALCON",
      "JAGUAR",
      "DRAGON",
      "TIGER",
      "VIPER",
      "COBRA",
      "EAGLE",
      "SHARK",
      "WOLF",
    ],
  },
  {
    name: "COSMIC ELEMENTS",
    themeColor: "#FFD700",
    words: [
      "BIOLUMINESCENCE",
      "SUPERCONDUCTOR",
      "INCANDESCENCE",
      "ELECTROMAGNET",
      "RADIOACTIVITY",
      "PHOSPHORESCENCE",
      "LIGHTNING",
      "CRYSTAL",
      "AURORA",
      "PLASMA",
      "VORTEX",
      "THUNDER",
      "SHADOW",
      "QUARTZ",
      "PRISM",
      "FLAME",
      "FROST",
      "SPARK",
      "BLAZE",
    ],
  },
  {
    name: "RETRO ARCADE",
    themeColor: "#E056FD",
    words: [
      "LEADERBOARD",
      "PLAYSTATION",
      "RETROSPECTIVE",
      "CHAMPIONSHIP",
      "CONTROLLER",
      "HIGHSCORE",
      "JOYSTICK",
      "POWERUP",
      "BONANZA",
      "INVADER",
      "PINBALL",
      "TETRIS",
      "REPLAY",
      "COMBO",
      "STAGE",
      "LEVEL",
      "BONUS",
      "COIN",
    ],
  },
  {
    name: "MYTHIC LEGENDS",
    themeColor: "#FF6B4A",
    words: [
      "LABYRINTH",
      "EXCALIBUR",
      "VALKYRIE",
      "MINOTAUR",
      "CENTAUR",
      "PEGASUS",
      "BASILISK",
      "CERBERUS",
      "HYDRA",
      "CHIMERA",
      "KRAKEN",
      "TITAN",
      "ORACLE",
      "GOLEM",
      "SIREN",
    ],
  },
];
